# Pair Programming - ANOVA

Hasta ahora habéis estado evaluando las características de vuestro set de datos y habéis hecho una gran exploración, es el momento de hacer vuestro primer ANOVA! En el ejercicio de hoy tendréis que hacer un ANOVA con vuestro datos y hacer una interpretación de los resultados.

NOTA Puede que vuestros datos no se ajusten o no cumplan todas las asunciones, no pasa nada, haced el ANOVA e interpretad los resultados. En próximas lecciones aprenderemos que podemos hacer cuando nos encontramos en esta situación.

In [9]:
import numpy as np
import pandas as pd
import random 

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.multivariate.manova import MANOVA
from sklearn.preprocessing import StandardScaler

import statsmodels.api as sm
from statsmodels.formula.api import ols

plt.rcParams["figure.figsize"] = (10,8)

In [10]:
df = pd.read_csv("data/adult.numericas_robust.csv", index_col = 0)

In [11]:
df.head(2)

,work_class,education,education_yrs,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_lost,hours_week,country,salary
39,,,,,,,,,,,,,
50,Self-emp-not-inc,Bachelors,-0.333333,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,-2.0,United-States,24006
38,Private,HS-grad,0.666667,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,0.0,United-States,44640

In [12]:
anova = ols('salary ~  work_class  + education + education_yrs + marital_status + occupation + relationship + ethnicity + gender + capital_gain + capital_lost + hours_week + country' , data = df).fit()
sm.stats.anova_lm(anova)

                     df        sum_sq       mean_sq           F         PR(>F)
work_class          8.0  3.872754e+12  4.840942e+11  129.361393  1.285960e-214
education          15.0  1.432693e+13  9.551286e+11  255.232866   0.000000e+00
marital_status      6.0  1.873749e+13  3.122915e+12  834.516606   0.000000e+00
occupation         14.0  1.848825e+12  1.320589e+11   35.289255   9.945621e-96
relationship        5.0  2.311637e+11  4.623274e+10   12.354478   5.367586e-12
ethnicity           4.0  6.761329e+10  1.690332e+10    4.516966   1.199383e-03
gender              1.0  3.719241e+11  3.719241e+11   99.386898   2.244144e-23
country            41.0  2.820830e+11  6.880072e+09    1.838518   8.612880e-04
education_yrs       1.0  1.476838e+10  1.476838e+10    3.946460   4.697847e-02
capital_gain        1.0  1.360261e+10  1.360261e+10    3.634938   5.658752e-02
capital_lost        1.0  7.257960e+09  7.257960e+09    1.939498   1.637326e-01
hours_week          1.0  3.940715e+10  3.940715e+10   10.530520   1.175380e-03
Residual        32462.0  1.214788e+14  3.742185e+09         NaN            NaN

**Interpretación de la ANOVA:** REINTERPRETAR: SALARY

Es importante recalcar previo a la interpretación que los datos con los que trabajamos no son normales.
- **df:** Las variables categóricas tienen más rango de libertad, mientras que las numéricas sólo uno. Esto es porque las numéricas sólo tienen el rango de los números naturales.
- **sum_sq:** Esta es la variación atribuida al error. Podemos observar que, en este caso, es mínima.
- **mean_sq:** Este es el producto de la dos columnas anteriores.
- **F:** ANOVA supone que las medias de todos los grupos son iguales, calcula cuánto se desvían las medias iguales de la suposición. Una puntuación mayor significa que hay mayor diferencia entre las medias, por lo tanto, las que tienen valores más próximos entre sí van a tener medias más similares.
- **PR(>F):** Aquí podemos observar que el p-valor es en todos los casos inferior a 0,05, con lo cual, debemos rechazar la hipótesis nula y concluimos que estas variables sí influyen en nuestra variable predictora.

In [13]:
anova.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.247
Model:                            OLS   Adj. R-squared:                  0.245
Method:                 Least Squares   F-statistic:                     109.7
Date:                Fri, 27 Jan 2023   Prob (F-statistic):               0.00
Time:                        18:22:49   Log-Likelihood:            -4.0501e+05
No. Observations:               32560   AIC:                         8.102e+05
Df Residuals:                   32462   BIC:                         8.110e+05
Df Model:                          97
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                 3.219e+04   6637.714      4.850      0.000    1.92e+04    4.52e+04
work_class[T. Federal-gov]                1.413e+04   2437.678      5.796      0.000    9351.054    1.89e+04
work_class[T. Local-gov]                  2091.2880   2096.454      0.998      0.319   -2017.839    6200.415
work_class[T. Never-worked]               2576.2835   2.32e+04      0.111      0.912   -4.29e+04     4.8e+04
work_class[T. Private]                    5017.8458   1667.918      3.008      0.003    1748.665    8287.027
work_class[T. Self-emp-inc]                2.04e+04   2426.083      8.408      0.000    1.56e+04    2.52e+04
work_class[T. Self-emp-not-inc]           -945.2674   2021.470     -0.468      0.640   -4907.423    3016.888
work_class[T. State-gov]                 -2460.1111   2312.047     -1.064      0.287   -6991.809    2071.587
work_class[T. Without-pay]               -1.923e+04   1.57e+04     -1.228      0.220   -4.99e+04    1.15e+04
education[T. 11th]                        1396.8677   2690.035      0.519      0.604   -3875.700    6669.435
education[T. 12th]                        5361.4851   3569.143      1.502      0.133   -1634.168    1.24e+04
education[T. 1st-4th]                    -4701.7002   5298.486     -0.887      0.375   -1.51e+04    5683.528
education[T. 5th-6th]                    -4244.3248   4113.264     -1.032      0.302   -1.23e+04    3817.826
education[T. 7th-8th]                    -8916.5367   3153.854     -2.827      0.005   -1.51e+04   -2734.866
education[T. 9th]                        -4853.4698   3375.535     -1.438      0.150   -1.15e+04    1762.704
education[T. Assoc-acdm]                  1.431e+04   2784.242      5.140      0.000    8854.688    1.98e+04
education[T. Assoc-voc]                   1.599e+04   2627.953      6.085      0.000    1.08e+04    2.11e+04
education[T. Bachelors]                   2.915e+04   2268.381     12.850      0.000    2.47e+04    3.36e+04
education[T. Doctorate]                   6.457e+04   3804.112     16.974      0.000    5.71e+04     7.2e+04
education[T. HS-grad]                     4922.4349   2104.034      2.340      0.019     798.451    9046.419
education[T. Masters]                     4.534e+04   2640.469     17.170      0.000    4.02e+04    5.05e+04
education[T. Preschool]                  -2701.7732   8892.832     -0.304      0.761   -2.01e+04    1.47e+04
education[T. Prof-school]                 6.499e+04   3442.241     18.880      0.000    5.82e+04    7.17e+04
education[T. Some-college]                1.025e+04   2156.991      4.750      0.000    6018.893    1.45e+04
marital_status[T. Married-AF-spouse]      2.213e+04   1.34e+04      1.653      0.098   -4105.339    4.84e+04
marital_status[T. Married-civ-spouse]     1.439e+04   4269.623      3.371      0.001    6025.977    2.28e+04
marital_status[T. Married-spouse-absent]  2821.1851   3173.441      0.889      0.374   -3398.877    9041.247
marital_status[T. Never-married]         -7162.8843   1212.806     -5.906      0.000   -9540.030   -4785.739
marital_status[T. Separated]              -155.5866   2137.202     -0.073      0.942   -4344.582    4033.409
marital_status[T. Widowed]                4732.2570   2178.987      2.172      0.030     461.362    9003.152
occupation[T. Adm-clerical]               2886.8893   1709.889      1.688      0.091    -464.557    6238.335
occupation[T. Armed-Forces]               -2.75e+04   1.95e+04     -1.407      0.159   -6.58e+04    1.08e+04
occupation[T. Craft-repair]                208.2059   1706.894      0.122      0.903   -3137.369    3553.781
occupation[T. Exec-managerial]            2.192e+04   1710.978     12.810      0.000    1.86e+04    2.53e+04
occupation[T. Farming-fishing]           -9017.3368   2348.339     -3.840      0.000   -1.36e+04   -4414.504
occupation[T. Handlers-cleaners]         -7150.1678   2141.146     -3.339      0.001   -1.13e+04   -2953.441
occupation[T. Machine-op-inspct]         -4749.4368   1948.868     -2.437      0.015   -8569.291    -929.583
occupation[T. Other-service]             -2794.6960   1749.251     -1.598      0.110   -6223.293     633.901
occupation[T. Priv-house-serv]            2846.3228   5062.700      0.562      0.574   -7076.758    1.28e+04
occupation[T. Prof-specialty]             1.207e+04   1789.849      6.743      0.000    8561.633    1.56e+04
occupation[T. Protective-serv]            1.556e+04   2757.605      5.641      0.000    1.02e+04     2.1e+04
occupation[T. Sales]                      7784.5669   1724.060      4.515      0.000    4405.346    1.12e+04
occupation[T. Tech-support]               1.002e+04   2391.933      4.188      0.000    5328.848    1.47e+04
occupation[T. Transport-moving]          -3073.6683   2052.218     -1.498      0.134   -7096.092     948.756
relationship[T. Not-in-family]            -2.43e+04   4250.072     -5.717      0.000   -3.26e+04    -1.6e+04
relationship[T. Other-relative]          -2.212e+04   4190.938     -5.277      0.000   -3.03e+04   -1.39e+04
relationship[T. Own-child]               -2.567e+04   4217.326     -6.087      0.000   -3.39e+04   -1.74e+04
relationship[T. Unmarried]               -2.327e+04   4397.137     -5.292      0.000   -3.19e+04   -1.47e+04
relationship[T. Wife]                      1.24e+04   1904.412      6.509      0.000    8663.978    1.61e+04
ethnicity[T. Asian-Pac-Islander]          8531.6869   4535.039      1.881      0.060    -357.157    1.74e+04
ethnicity[T. Black]                       6323.2146   3655.521      1.730      0.084    -841.742    1.35e+04
ethnicity[T. Other]                       2465.0016   5175.966      0.476      0.634   -7680.083    1.26e+04
ethnicity[T. White]                       8140.2520   3499.944      2.326      0.020    1280.231     1.5e+04
gender[T. Male]                           1.029e+04   1017.355     10.113      0.000    8294.567    1.23e+04
country[T. Cambodia]                      2.967e+04   1.45e+04      2.050      0.040    1296.103     5.8e+04
country[T. Canada]                        1.418e+04   6134.083      2.311      0.021    2154.903    2.62e+04
country[T. China]                         -1.43e+04   7916.344     -1.806      0.071   -2.98e+04    1218.979
country[T. Columbia]                     -1.163e+04   8389.305     -1.386      0.166   -2.81e+04    4814.422
country[T. Cuba]                          9645.5347   6791.477      1.420      0.156   -3666.012     2.3e+04
country[T. Dominican-Republic]            1089.6597   7834.556      0.139      0.889   -1.43e+04    1.64e+04
country[T. Ecuador]                      -1.247e+04   1.19e+04     -1.046      0.295   -3.58e+04    1.09e+04
country[T. El-Salvador]                   2271.9543   6549.486      0.347      0.729   -1.06e+04    1.51e+04
country[T. England]                       1.175e+04   6949.559      1.690      0.091   -1874.296    2.54e+04
country[T. France]                        1.634e+04   1.17e+04      1.401      0.161   -6522.624    3.92e+04
country[T. Germany]                       1.107e+04   5829.850      1.899      0.058    -358.743    2.25e+04
country[T. Greece]                       -3048.3897   1.17e+04     -0.261      0.794   -2.59e+04    1.98e+04
country[T. Guatemala]                     8520.5464   8172.621      1.043      0.297   -7498.094    2.45e+04
country[T. Haiti]                         5411.8950   9633.720      0.562      0.574   -1.35e+04    2.43e+04
country[T. Holand-Netherlands]            1.323e+04   6.13e+04      0.216      0.829   -1.07e+05    1.33e+05
country[T. Honduras]                     -1.215e+04   1.72e+04     -0.707      0.480   -4.58e+04    2.15e+04
country[T. Hong]                         -3154.9950   1.41e+04     -0.224      0.823   -3.08e+04    2.45e+04
country[T. Hungary]                       5125.4193   1.72e+04      0.298      0.765   -2.85e+04    3.88e+04
country[T. India]                        -1.147e+04   6971.070     -1.646      0.100   -2.51e+04    2192.438
country[T. Iran]                          1.068e+04   9679.844      1.103      0.270   -8295.243    2.97e+04
country[T. Ireland]                       1.238e+04   1.28e+04      0.970      0.332   -1.26e+04    3.74e+04
country[T. Italy]                         1.178e+04   7634.392      1.543      0.123   -3185.910    2.67e+04
country[T. Jamaica]                       1852.8514   7331.126      0.253      0.800   -1.25e+04    1.62e+04
country[T. Japan]                         2.166e+04   8296.895      2.610      0.009    5393.852    3.79e+04
country[T. Laos]                         -4021.8829   1.49e+04     -0.270      0.787   -3.32e+04    2.52e+04
country[T. Mexico]                       -3237.4180   3687.140     -0.878      0.380   -1.05e+04    3989.514
country[T. Nicaragua]                    -8340.1438   1.08e+04     -0.771      0.441   -2.96e+04    1.29e+04
country[T. Outlying-US(Guam-USVI-etc)]   -9566.5562   1.66e+04     -0.578      0.564    -4.2e+04    2.29e+04
country[T. Peru]                          1173.8188   1.13e+04      0.104      0.917    -2.1e+04    2.33e+04
country[T. Philippines]                   1.215e+04   5577.479      2.178      0.029    1214.708    2.31e+04
country[T. Poland]                       -1125.4936   8316.438     -0.135      0.892   -1.74e+04    1.52e+04
country[T. Portugal]                     -1593.4251   1.04e+04     -0.153      0.879   -2.21e+04    1.89e+04
country[T. Puerto-Rico]                   2237.3740   6321.991      0.354      0.723   -1.02e+04    1.46e+04
country[T. Scotland]                     -1522.0548   1.79e+04     -0.085      0.932   -3.65e+04    3.35e+04
country[T. South]                        -8150.8872   7696.572     -1.059      0.290   -2.32e+04    6934.680
country[T. Taiwan]                       -1.327e+04   9258.208     -1.434      0.152   -3.14e+04    4872.240
country[T. Thailand]                     -1.047e+04   1.48e+04     -0.707      0.480   -3.95e+04    1.86e+04
country[T. Trinadad&Tobago]                182.6045   1.43e+04      0.013      0.990   -2.78e+04    2.82e+04
country[T. United-States]                 6666.1863   2606.397      2.558      0.011    1557.552    1.18e+04
country[T. Vietnam]                      -8152.1315   8271.613     -0.986      0.324   -2.44e+04    8060.537
country[T. Yugoslavia]                    3883.1766   1.55e+04      0.250      0.802   -2.65e+04    3.43e+04
education_yrs                             1110.0159    400.857      2.769      0.006     324.321    1895.711
capital_gain                                 0.9987      0.557      1.793      0.073      -0.093       2.090
capital_lost                                -0.9052      0.762     -1.187      0.235      -2.399       0.589
hours_week                                -512.1890    157.232     -3.258      0.001    -820.369    -204.009
==============================================================================
Omnibus:                     8120.263   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            18027.011
Skew:                           1.437   Prob(JB):                         0.00
Kurtosis:                       5.242   Cond. No.                     4.60e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.9e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

R-cuadrado = Variación explicada / variación total
El R-cuadrado siempre está entre 0 y 100%:
0% indica que el modelo no explica ninguna porción de la variabilidad de los datos de respuesta en torno a su media.
100% indica que el modelo explica toda la variabilidad de los datos de respuesta en torno a su media.

**Interpretación del summary**

- **R-square:** Siempre se encuentra entre el 0 y el 100%, el nuestro está en 0.247, por lo tanto, esto nos quiere decir que la variables presidctoras explican en un 24,7% nuestra variable respuesta.
- **coef:** Estos datos nos indican cuánto son afectadas las variables por las que se relacionan con ellas. Vemos que las afectaciones son mínimas, de muy poquitas milésimas, tanto en positivo como en negativo.
- **std err:** Esta columna nos está diciendo que tenemos un gran margen de error en la estimación del coeficiente, seguramente debido a la cantidad de ouliers.
- **t:** Es el resultado de dividir los dos valores anteriores. Con esto estamos intentando averiguar en qué medida la afectación de los datos entre sí influye en el margen de error, es decir, si las variables se influyen también cuando no tienen correlación.

No obstante, dado que nuestros datos ni son normales ni cumplen ninguna de las asunciones, es ejercicio no es necesario. Con lo cual, no nos extraña que las conclusiones que extraemos de él sean estas.