# Pair Programming - ANOVA

Hasta ahora habéis estado evaluando las características de vuestro set de datos y habéis hecho una gran exploración, es el momento de hacer vuestro primer ANOVA! En el ejercicio de hoy tendréis que hacer un ANOVA con vuestro datos y hacer una interpretación de los resultados.

NOTA Puede que vuestros datos no se ajusten o no cumplan todas las asunciones, no pasa nada, haced el ANOVA e interpretad los resultados. En próximas lecciones aprenderemos que podemos hacer cuando nos encontramos en esta situación.

In [1]:
import numpy as np
import pandas as pd
import random 

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.multivariate.manova import MANOVA
from sklearn.preprocessing import StandardScaler

import statsmodels.api as sm
from statsmodels.formula.api import ols

plt.rcParams["figure.figsize"] = (10,8)

/home/adalaber/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:7: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
/home/adalaber/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:7: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,

In [2]:
df = pd.read_csv("data/adult.data_limpio.csv", index_col = 0)

In [3]:
df.head(2)

,work_class,final_weight,education,education_yrs,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_lost,hours_week,country,salary,census
39,,,,,,,,,,,,,,,
50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,32755,Bajo
38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,45156,Bajo

In [4]:
anova = ols('salary ~ final_weight + work_class  + education + education_yrs + marital_status + occupation + relationship + ethnicity + gender + capital_gain + capital_lost + hours_week + country + census' , data=df).fit()
sm.stats.anova_lm(anova)

                     df        sum_sq       mean_sq           F         PR(>F)
work_class          8.0  3.613460e+12  4.516825e+11  124.282201  4.119752e-206
education          15.0  1.428010e+13  9.520068e+11  261.948406   0.000000e+00
marital_status      6.0  1.876751e+13  3.127918e+12  860.658907   0.000000e+00
occupation         14.0  2.157773e+12  1.541266e+11   42.408545  1.515002e-116
relationship        5.0  2.766719e+11  5.533439e+10   15.225473   5.638438e-15
ethnicity           4.0  4.046129e+10  1.011532e+10    2.783270   2.512505e-02
gender              1.0  3.921565e+11  3.921565e+11  107.903405   3.091255e-25
country            41.0  2.424761e+11  5.914050e+09    1.627274   6.809596e-03
census              1.0  3.659677e+09  3.659677e+09    1.006974   3.156362e-01
final_weight        1.0  1.676260e+10  1.676260e+10    4.612296   3.175089e-02
education_yrs       1.0  4.813726e+09  4.813726e+09    1.324516   2.497917e-01
capital_gain        1.0  1.980902e+12  1.980902e+12  545.052937  1.453712e-119
capital_lost        1.0  8.951405e+11  8.951405e+11  246.301408   2.656526e-55
hours_week          1.0  6.565243e+11  6.565243e+11  180.645243   4.513209e-41
Residual        32461.0  1.179740e+14  3.634329e+09         NaN            NaN

**Interpretación de la ANOVA:** REINTERPRETAR: SALARY

Es importante recalcar previo a la interpretación que los datos con los que trabajamos no son normales.
- **df:** Las variables categóricas tienen más rango de libertad, mientras que las numéricas sólo uno. Esto es porque las numéricas sólo tienen el rango de los números naturales.
- **sum_sq:** Esta es la variación atribuida al error. Podemos observar que, en este caso, es mínima.
- **mean_sq:** Este es el producto de la dos columnas anteriores.
- **F:** ANOVA supone que las medias de todos los grupos son iguales, calcula cuánto se desvían las medias iguales de la suposición. Una puntuación mayor significa que hay mayor diferencia entre las medias, por lo tanto, las que tienen valores más próximos entre sí van a tener medias más similares.
- **PR(>F):** Aquí podemos observar que el p-valor es en todos los casos inferior a 0,05, con lo cual, debemos rechazar la hipótesis nula y concluimos que estas variables sí influyen en nuestra variable predictora.

In [5]:
anova.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.269
Model:                            OLS   Adj. R-squared:                  0.266
Method:                 Least Squares   F-statistic:                     121.6
Date:                Thu, 26 Jan 2023   Prob (F-statistic):               0.00
Time:                        12:44:17   Log-Likelihood:            -4.0453e+05
No. Observations:               32560   AIC:                         8.093e+05
Df Residuals:                   32461   BIC:                         8.101e+05
Df Model:                          98
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                 -943.1629   1.13e+04     -0.083      0.934   -2.31e+04    2.13e+04
work_class[T. Federal-gov]                1.055e+04   2406.120      4.386      0.000    5837.808    1.53e+04
work_class[T. Local-gov]                  -667.0649   2070.288     -0.322      0.747   -4724.906    3390.777
work_class[T. Never-worked]               -134.9263   2.28e+04     -0.006      0.995   -4.49e+04    4.46e+04
work_class[T. Private]                    2883.9521   1649.575      1.748      0.080    -349.275    6117.180
work_class[T. Self-emp-inc]               1.246e+04   2410.488      5.168      0.000    7731.673    1.72e+04
work_class[T. Self-emp-not-inc]          -4106.2756   1999.477     -2.054      0.040   -8025.325    -187.226
work_class[T. State-gov]                 -2281.5936   2279.933     -1.001      0.317   -6750.347    2187.160
work_class[T. Without-pay]                -1.16e+04   1.54e+04     -0.752      0.452   -4.19e+04    1.87e+04
education[T. 11th]                        -782.2414   2553.417     -0.306      0.759   -5787.034    4222.551
education[T. 12th]                       -1490.2936   3372.827     -0.442      0.659   -8101.160    5120.573
education[T. 1st-4th]                     1.446e+04   5358.610      2.698      0.007    3953.442     2.5e+04
education[T. 5th-6th]                     9596.3631   4246.724      2.260      0.024    1272.626    1.79e+04
education[T. 7th-8th]                      158.1546   3301.310      0.048      0.962   -6312.535    6628.845
education[T. 9th]                          -90.9235   3411.496     -0.027      0.979   -6777.583    6595.736
education[T. Assoc-acdm]                 -1.109e+04   2384.234     -4.652      0.000   -1.58e+04   -6417.998
education[T. Assoc-voc]                  -5889.5922   2246.218     -2.622      0.009   -1.03e+04   -1486.923
education[T. Bachelors]                   -783.2517   1883.200     -0.416      0.677   -4474.393    2907.889
education[T. Doctorate]                   1.809e+04   3132.667      5.774      0.000    1.19e+04    2.42e+04
education[T. HS-grad]                    -7465.3204   1772.259     -4.212      0.000   -1.09e+04   -3991.628
education[T. Masters]                     7294.4408   2230.010      3.271      0.001    2923.539    1.17e+04
education[T. Preschool]                   1.835e+04   8573.414      2.140      0.032    1540.920    3.51e+04
education[T. Prof-school]                 1.075e+04   2888.188      3.722      0.000    5089.307    1.64e+04
education[T. Some-college]               -5037.6044   1778.971     -2.832      0.005   -8524.454   -1550.755
marital_status[T. Married-AF-spouse]      9898.7537   1.32e+04      0.751      0.453    -1.6e+04    3.57e+04
marital_status[T. Married-civ-spouse]      1.31e+04   4207.416      3.113      0.002    4852.519    2.13e+04
marital_status[T. Married-spouse-absent]  2081.6985   3127.470      0.666      0.506   -4048.260    8211.657
marital_status[T. Never-married]         -5807.4890   1193.064     -4.868      0.000   -8145.939   -3469.039
marital_status[T. Separated]               774.0169   2106.291      0.367      0.713   -3354.391    4902.425
marital_status[T. Widowed]                6722.3321   2154.850      3.120      0.002    2498.746    1.09e+04
occupation[T. Adm-clerical]               1473.6123   1685.138      0.874      0.382   -1829.320    4776.545
occupation[T. Armed-Forces]              -1.991e+04   1.93e+04     -1.033      0.301   -5.77e+04    1.78e+04
occupation[T. Craft-repair]              -1941.2228   1683.347     -1.153      0.249   -5240.646    1358.200
occupation[T. Exec-managerial]             1.97e+04   1691.523     11.646      0.000    1.64e+04     2.3e+04
occupation[T. Farming-fishing]            -1.44e+04   2325.195     -6.194      0.000    -1.9e+04   -9843.877
occupation[T. Handlers-cleaners]         -7924.4307   2110.119     -3.755      0.000   -1.21e+04   -3788.520
occupation[T. Machine-op-inspct]         -5854.8415   1921.742     -3.047      0.002   -9621.527   -2088.156
occupation[T. Other-service]             -2811.3989   1724.764     -1.630      0.103   -6192.000     569.203
occupation[T. Priv-house-serv]            3388.3574   4989.686      0.679      0.497   -6391.613    1.32e+04
occupation[T. Prof-specialty]             1.121e+04   1764.631      6.351      0.000    7748.646    1.47e+04
occupation[T. Protective-serv]            1.025e+04   2719.845      3.767      0.000    4915.080    1.56e+04
occupation[T. Sales]                      7248.8815   1699.870      4.264      0.000    3917.074    1.06e+04
occupation[T. Tech-support]               1.206e+04   2357.096      5.115      0.000    7437.440    1.67e+04
occupation[T. Transport-moving]          -5245.3626   2028.084     -2.586      0.010   -9220.482   -1270.243
relationship[T. Not-in-family]           -2.481e+04   4188.881     -5.924      0.000    -3.3e+04   -1.66e+04
relationship[T. Other-relative]          -2.159e+04   4130.279     -5.227      0.000   -2.97e+04   -1.35e+04
relationship[T. Own-child]               -2.429e+04   4157.621     -5.841      0.000   -3.24e+04   -1.61e+04
relationship[T. Unmarried]               -2.406e+04   4333.683     -5.553      0.000   -3.26e+04   -1.56e+04
relationship[T. Wife]                     1.511e+04   1878.876      8.040      0.000    1.14e+04    1.88e+04
ethnicity[T. Asian-Pac-Islander]          3569.2025   4469.181      0.799      0.425   -5190.557    1.23e+04
ethnicity[T. Black]                       4966.6946   3620.260      1.372      0.170   -2129.148    1.21e+04
ethnicity[T. Other]                       2422.4142   5103.846      0.475      0.635   -7581.312    1.24e+04
ethnicity[T. White]                       5852.0980   3455.838      1.693      0.090    -921.473    1.26e+04
gender[T. Male]                           8755.7065   1007.328      8.692      0.000    6781.305    1.07e+04
country[T. Cambodia]                      3.319e+04   1.43e+04      2.327      0.020    5228.707    6.12e+04
country[T. Canada]                        6663.8681   6044.739      1.102      0.270   -5184.044    1.85e+04
country[T. China]                        -7268.3200   7803.131     -0.931      0.352   -2.26e+04    8026.105
country[T. Columbia]                     -7827.0405   8269.745     -0.946      0.344    -2.4e+04    8381.966
country[T. Cuba]                          2059.7635   6695.919      0.308      0.758   -1.11e+04    1.52e+04
country[T. Dominican-Republic]           -3881.6400   7720.948     -0.503      0.615    -1.9e+04    1.13e+04
country[T. Ecuador]                      -4769.4906   1.17e+04     -0.406      0.685   -2.78e+04    1.82e+04
country[T. El-Salvador]                    926.9345   6457.694      0.144      0.886   -1.17e+04    1.36e+04
country[T. England]                       6180.2751   6848.802      0.902      0.367   -7243.630    1.96e+04
country[T. France]                        2.178e+04   1.15e+04      1.895      0.058    -750.002    4.43e+04
country[T. Germany]                       6766.5852   5745.424      1.178      0.239   -4494.660     1.8e+04
country[T. Greece]                       -1.319e+04   1.15e+04     -1.148      0.251   -3.57e+04    9331.774
country[T. Guatemala]                     3271.2153   8057.420      0.406      0.685   -1.25e+04    1.91e+04
country[T. Haiti]                           -1.4477   9493.863     -0.000      1.000   -1.86e+04    1.86e+04
country[T. Holand-Netherlands]           -2.247e+04   6.04e+04     -0.372      0.710   -1.41e+05     9.6e+04
country[T. Honduras]                      8505.8585   1.69e+04      0.502      0.616   -2.47e+04    4.17e+04
country[T. Hong]                          8332.6005   1.39e+04      0.600      0.548   -1.89e+04    3.56e+04
country[T. Hungary]                      -1.585e+04   1.69e+04     -0.936      0.349    -4.9e+04    1.73e+04
country[T. India]                          760.8341   6869.608      0.111      0.912   -1.27e+04    1.42e+04
country[T. Iran]                          1.297e+04   9539.056      1.360      0.174   -5727.233    3.17e+04
country[T. Ireland]                       1.674e+04   1.26e+04      1.331      0.183   -7912.496    4.14e+04
country[T. Italy]                         1.831e+04   7523.789      2.434      0.015    3564.028    3.31e+04
country[T. Jamaica]                       7627.4187   7225.119      1.056      0.291   -6534.083    2.18e+04
country[T. Japan]                         1.584e+04   8176.052      1.937      0.053    -184.896    3.19e+04
country[T. Laos]                         -1.121e+04   1.47e+04     -0.764      0.445      -4e+04    1.75e+04
country[T. Mexico]                       -4496.0645   3649.137     -1.232      0.218   -1.16e+04    2656.379
country[T. Nicaragua]                    -7821.7413   1.07e+04     -0.733      0.464   -2.87e+04    1.31e+04
country[T. Outlying-US(Guam-USVI-etc)]    -1.78e+04   1.63e+04     -1.091      0.275   -4.98e+04    1.42e+04
country[T. Peru]                           709.4247   1.11e+04      0.064      0.949   -2.11e+04    2.25e+04
country[T. Philippines]                   1.224e+04   5496.433      2.226      0.026    1464.127     2.3e+04
country[T. Poland]                         816.5198   8195.119      0.100      0.921   -1.52e+04    1.69e+04
country[T. Portugal]                     -3667.8431   1.03e+04     -0.356      0.721   -2.38e+04    1.65e+04
country[T. Puerto-Rico]                   3578.8482   6230.335      0.574      0.566   -8632.839    1.58e+04
country[T. Scotland]                      9957.8451   1.76e+04      0.566      0.572   -2.45e+04    4.45e+04
country[T. South]                         1658.3735   7585.087      0.219      0.827   -1.32e+04    1.65e+04
country[T. Taiwan]                        2089.1123   9124.858      0.229      0.819   -1.58e+04       2e+04
country[T. Thailand]                      1588.2702   1.46e+04      0.109      0.913    -2.7e+04    3.02e+04
country[T. Trinadad&Tobago]               -878.1767   1.41e+04     -0.062      0.950   -2.85e+04    2.67e+04
country[T. United-States]                 7298.1854   2568.578      2.841      0.004    2263.677    1.23e+04
country[T. Vietnam]                      -3979.3232   8151.583     -0.488      0.625      -2e+04     1.2e+04
country[T. Yugoslavia]                     1.82e+04   1.53e+04      1.190      0.234   -1.18e+04    4.82e+04
census[T.Bajo]                           -3833.8899   9880.741     -0.388      0.698   -2.32e+04    1.55e+04
final_weight                                 0.0074      0.003      2.195      0.028       0.001       0.014
education_yrs                             3990.7330    259.172     15.398      0.000    3482.747    4498.719
capital_gain                                 1.1076      0.047     23.788      0.000       1.016       1.199
capital_lost                                12.9302      0.839     15.411      0.000      11.286      14.575
hours_week                                 404.1988     30.041     13.455      0.000     345.318     463.079
==============================================================================
Omnibus:                     8031.420   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            17894.693
Skew:                           1.418   Prob(JB):                         0.00
Kurtosis:                       5.269   Cond. No.                     3.20e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.5e-20. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

R-cuadrado = Variación explicada / variación total
El R-cuadrado siempre está entre 0 y 100%:
0% indica que el modelo no explica ninguna porción de la variabilidad de los datos de respuesta en torno a su media.
100% indica que el modelo explica toda la variabilidad de los datos de respuesta en torno a su media.

**Interpretación del summary**

- **R-square:** Siempre se encuentra entre el 0 y el 100%, el nuestro está en 0.117, por lo tanto, esto nos quiere decir que la variables presidctoras explican en un 11,7% nuestra variable respuesta.
- **coef:** Estos datos nos indican cuánto son afectadas las variables por las que se relacionan con ellas. Vemos que las afectaciones son mínimas, de muy poquitas milésimas, tanto en positivo como en negativo.
- **std err:** Esta columna nos está diciendo que tenemos un gran margen de error en la estimación del coeficiente, seguramente debido a la cantidad de ouliers.
- **t:** Es el resultado de dividir los dos valores anteriores. Con esto estamos intentando averiguar en qué medida la afectación de los datos entre sí influye en el margen de error, es decir, si las variables se influyen también cuando no tienen correlación (or something???).