### Pair Programming - ANOVA

Hasta ahora habéis estado evaluando las características de vuestro set de datos y habéis hecho una gran exploración, es el momento de hacer vuestro primer ANOVA! En el ejercicio de hoy tendréis que hacer un ANOVA con vuestro datos y hacer una interpretación de los resultados.

NOTA Puede que vuestros datos no se ajusten o no cumplan todas las asunciones, no pasa nada, haced el ANOVA e interpretad los resultados. En próximas lecciones aprenderemos que podemos hacer cuando nos encontramos en esta situación.

In [14]:
import numpy as np
import pandas as pd
import random 

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.multivariate.manova import MANOVA
from sklearn.preprocessing import StandardScaler

import statsmodels.api as sm
from statsmodels.formula.api import ols

plt.rcParams["figure.figsize"] = (10,8)

In [15]:
df = pd.read_csv("data/adult.data_limpio.csv", index_col = 0)

In [16]:
df.head(2)

,work_class,final_weight,education,education_yrs,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_lost,hours_week,country,salary,census
39,,,,,,,,,,,,,,,
50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,Bajo
38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,Bajo

In [17]:
anova = ols('final_weight ~ work_class  + education + education_yrs + marital_status + occupation + relationship + ethnicity + gender + capital_gain + capital_lost + hours_week + country + salary + census' , data=df).fit()
sm.stats.anova_lm(anova)

,df,sum_sq,mean_sq,F,PR(>F)
work_class,8.0,1.003162e+12,1.253952e+11,12.705783,2.109971e-18
education,15.0,1.503840e+12,1.002560e+11,10.158531,9.434647e-25
marital_status,6.0,8.366524e+11,1.394421e+11,14.129096,3.865187e-16
occupation,14.0,7.278147e+11,5.198676e+10,5.267606,4.135104e-10
relationship,5.0,1.507296e+11,3.014592e+10,3.054563,9.269151e-03
ethnicity,4.0,6.669374e+12,1.667343e+12,168.945106,1.922569e-143
gender,1.0,6.698914e+11,6.698914e+11,67.877359,1.804504e-16
country,41.0,8.188998e+12,1.997317e+11,20.237994,1.635877e-145
salary,1.0,9.944195e+10,9.944195e+10,10.076046,1.503495e-03
census,1.0,2.243753e+13,2.243753e+13,2273.503608,0.000000e+00
education_yrs,1.0,1.422502e+09,1.422502e+09,0.144136,7.042056e-01
capital_gain,1.0,8.264308e+09,8.264308e+09,0.837389,3.601515e-01
capital_lost,1.0,8.493063e+09,8.493063e+09,0.860567,3.535869e-01
hours_week,1.0,6.806454e+10,6.806454e+10,6.896702,8.639543e-03
Residual,32461.0,3.203623e+14,9.869143e+09,NaN,NaN

**Interpretación de la ANOVA:**

Es importante recalcar previo a la interpretación que los datos con los que trabajamos no son normales.
- **df:** Las variables categóricas tienen más rango de libertad, mientras que las numéricas sólo uno. Esto es porque las numéricas sólo tienen el rango de los números naturales.
- **sum_sq:** Esta es la variación atribuida al error. Podemos observar que, en este caso, es mínima.
- **mean_sq:** Este es el producto de la dos columnas anteriores.
- **F:** ANOVA supone que las medias de todos los grupos son iguales, calcula cuánto se desvían las medias iguales de la suposición. Una puntuación mayor significa que hay mayor diferencia entre las medias, por lo tanto, las que tienen valores más próximos entre sí van a tener medias más similares.
- **PR(>F):** Aquí podemos observar que el p-valor es en todos los casos inferior a 0,05, con lo cual, debemos rechazar la hipótesis nula y concluimos que estas variables sí influyen en nuestra variable predictora.

In [18]:
anova.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           final_weight   R-squared:                       0.117
Model:                            OLS   Adj. R-squared:                  0.114
Method:                 Least Squares   F-statistic:                     43.81
Date:                Mon, 23 Jan 2023   Prob (F-statistic):               0.00
Time:                        10:30:26   Log-Likelihood:            -4.2080e+05
No. Observations:               32560   AIC:                         8.418e+05
Df Residuals:                   32461   BIC:                         8.426e+05
Df Model:                          98
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                 8.025e+05   1.81e+04     44.271      0.000    7.67e+05    8.38e+05
work_class[T. Federal-gov]               -3546.4328   3968.538     -0.894      0.372   -1.13e+04    4232.049
work_class[T. Local-gov]                  2763.8696   3411.569      0.810      0.418   -3922.932    9450.671
work_class[T. Never-worked]               2.651e+04   3.76e+04      0.704      0.481   -4.73e+04       1e+05
work_class[T. Private]                    5126.6299   2718.461      1.886      0.059    -201.655    1.05e+04
work_class[T. Self-emp-inc]              -6796.9065   3975.090     -1.710      0.087   -1.46e+04     994.418
work_class[T. Self-emp-not-inc]          -3479.4005   3295.188     -1.056      0.291   -9938.091    2979.290
work_class[T. State-gov]                 -1687.2137   3757.164     -0.449      0.653   -9051.394    5676.967
work_class[T. Without-pay]                2041.2730   2.54e+04      0.080      0.936   -4.78e+04    5.19e+04
education[T. 11th]                       -1.356e+04   4207.093     -3.223      0.001   -2.18e+04   -5313.387
education[T. 12th]                       -2.586e+04   5556.213     -4.654      0.000   -3.68e+04    -1.5e+04
education[T. 1st-4th]                     3.964e+04   8828.418      4.490      0.000    2.23e+04    5.69e+04
education[T. 5th-6th]                     2.125e+04   6997.647      3.036      0.002    7531.677     3.5e+04
education[T. 7th-8th]                     9858.0903   5439.919      1.812      0.070    -804.353    2.05e+04
education[T. 9th]                         4387.1102   5621.711      0.780      0.435   -6631.652    1.54e+04
education[T. Assoc-acdm]                  -6.26e+04   3914.679    -15.991      0.000   -7.03e+04   -5.49e+04
education[T. Assoc-voc]                  -6.132e+04   3686.143    -16.636      0.000   -6.85e+04   -5.41e+04
education[T. Bachelors]                  -7.771e+04   3073.271    -25.287      0.000   -8.37e+04   -7.17e+04
education[T. Doctorate]                  -1.075e+05   5133.910    -20.941      0.000   -1.18e+05   -9.74e+04
education[T. HS-grad]                     -3.57e+04   2914.569    -12.250      0.000   -4.14e+04      -3e+04
education[T. Masters]                    -9.429e+04   3639.926    -25.904      0.000   -1.01e+05   -8.72e+04
education[T. Preschool]                   5.295e+04   1.41e+04      3.749      0.000    2.53e+04    8.06e+04
education[T. Prof-school]                -9.734e+04   4732.540    -20.569      0.000   -1.07e+05   -8.81e+04
education[T. Some-college]               -4.733e+04   2920.024    -16.208      0.000   -5.31e+04   -4.16e+04
marital_status[T. Married-AF-spouse]      1.666e+04   2.17e+04      0.766      0.443   -2.59e+04    5.93e+04
marital_status[T. Married-civ-spouse]     9123.6804   6934.976      1.316      0.188   -4469.130    2.27e+04
marital_status[T. Married-spouse-absent] -5974.8964   5153.726     -1.159      0.246   -1.61e+04    4126.598
marital_status[T. Never-married]          4938.2412   1966.855      2.511      0.012    1083.133    8793.349
marital_status[T. Separated]              9674.8843   3470.523      2.788      0.005    2872.531    1.65e+04
marital_status[T. Widowed]               -9099.8388   3551.658     -2.562      0.010   -1.61e+04   -2138.457
occupation[T. Adm-clerical]               2956.6322   2776.925      1.065      0.287   -2486.244    8399.509
occupation[T. Armed-Forces]                3.24e+04   3.17e+04      1.021      0.307   -2.98e+04    9.46e+04
occupation[T. Craft-repair]               -969.3801   2773.999     -0.349      0.727   -6406.521    4467.761
occupation[T. Exec-managerial]           -1741.1899   2796.652     -0.623      0.534   -7222.732    3740.352
occupation[T. Farming-fishing]           -2.265e+04   3832.524     -5.909      0.000   -3.02e+04   -1.51e+04
occupation[T. Handlers-cleaners]           954.1784   3478.321      0.274      0.784   -5863.459    7771.816
occupation[T. Machine-op-inspct]         -3915.5692   3167.455     -1.236      0.216   -1.01e+04    2292.760
occupation[T. Other-service]             -1.027e+04   2841.786     -3.613      0.000   -1.58e+04   -4698.129
occupation[T. Priv-house-serv]           -1.108e+04   8222.334     -1.347      0.178   -2.72e+04    5039.321
occupation[T. Prof-specialty]             -303.0847   2910.468     -0.104      0.917   -6007.709    5401.540
occupation[T. Protective-serv]            8495.3289   4483.561      1.895      0.058    -292.617    1.73e+04
occupation[T. Sales]                      1097.1812   2802.291      0.392      0.695   -4395.414    6589.776
occupation[T. Tech-support]               2339.8294   3886.289      0.602      0.547   -5277.442    9957.101
occupation[T. Transport-moving]          -2900.2812   3342.422     -0.868      0.386   -9451.552    3650.989
relationship[T. Not-in-family]            1.572e+04   6907.948      2.275      0.023    2176.316    2.93e+04
relationship[T. Other-relative]           1.583e+04   6810.050      2.324      0.020    2478.250    2.92e+04
relationship[T. Own-child]                1.397e+04   6856.307      2.038      0.042     534.350    2.74e+04
relationship[T. Unmarried]                1.289e+04   7146.058      1.804      0.071   -1117.547    2.69e+04
relationship[T. Wife]                     3812.3515   3100.640      1.230      0.219   -2265.019    9889.722
ethnicity[T. Asian-Pac-Islander]          2.213e+04   7363.991      3.005      0.003    7694.538    3.66e+04
ethnicity[T. Black]                        1.07e+05   5936.421     18.021      0.000    9.53e+04    1.19e+05
ethnicity[T. Other]                       5.486e+04   8405.051      6.527      0.000    3.84e+04    7.13e+04
ethnicity[T. White]                       6.493e+04   5683.924     11.424      0.000    5.38e+04    7.61e+04
gender[T. Male]                           1.267e+04   1661.286      7.627      0.000    9413.770    1.59e+04
country[T. Cambodia]                      3.517e+04   2.35e+04      1.496      0.135   -1.09e+04    8.13e+04
country[T. Canada]                       -1.249e+04   9961.507     -1.254      0.210    -3.2e+04    7032.766
country[T. China]                         2.926e+04   1.29e+04      2.275      0.023    4055.561    5.45e+04
country[T. Columbia]                      2.189e+04   1.36e+04      1.607      0.108   -4815.505    4.86e+04
country[T. Cuba]                          5.474e+04    1.1e+04      4.963      0.000    3.31e+04    7.64e+04
country[T. Dominican-Republic]           -2537.5035   1.27e+04     -0.199      0.842   -2.75e+04    2.24e+04
country[T. Ecuador]                      -5056.9804   1.93e+04     -0.261      0.794    -4.3e+04    3.29e+04
country[T. El-Salvador]                   5.521e+04   1.06e+04      5.190      0.000    3.44e+04    7.61e+04
country[T. England]                      -1.456e+04   1.13e+04     -1.290      0.197   -3.67e+04    7565.699
country[T. France]                        -881.5630   1.89e+04     -0.047      0.963    -3.8e+04    3.62e+04
country[T. Germany]                      -4479.8395   9468.692     -0.473      0.636    -2.3e+04    1.41e+04
country[T. Greece]                       -4.508e+04   1.89e+04     -2.381      0.017   -8.22e+04   -7975.705
country[T. Guatemala]                     7.269e+04   1.33e+04      5.477      0.000    4.67e+04    9.87e+04
country[T. Haiti]                        -2.206e+04   1.56e+04     -1.410      0.158   -5.27e+04    8601.350
country[T. Holand-Netherlands]           -1.591e+05   9.96e+04     -1.598      0.110   -3.54e+05    3.61e+04
country[T. Honduras]                      5.924e+04   2.79e+04      2.123      0.034    4540.648    1.14e+05
country[T. Hong]                          6.682e+04   2.29e+04      2.921      0.003     2.2e+04    1.12e+05
country[T. Hungary]                      -9855.8919   2.79e+04     -0.353      0.724   -6.45e+04    4.48e+04
country[T. India]                         9037.2955   1.13e+04      0.798      0.425   -1.32e+04    3.12e+04
country[T. Iran]                         -4473.1930   1.57e+04     -0.285      0.776   -3.53e+04    2.63e+04
country[T. Ireland]                      -5.585e+04   2.07e+04     -2.695      0.007   -9.65e+04   -1.52e+04
country[T. Italy]                        -8528.6216   1.24e+04     -0.688      0.492   -3.28e+04    1.58e+04
country[T. Jamaica]                      -1.983e+04   1.19e+04     -1.666      0.096   -4.32e+04    3502.089
country[T. Japan]                         1.717e+04   1.35e+04      1.274      0.203   -9241.199    4.36e+04
country[T. Laos]                          6.205e+04   2.42e+04      2.567      0.010    1.47e+04    1.09e+05
country[T. Mexico]                        9.883e+04   5988.369     16.504      0.000    8.71e+04    1.11e+05
country[T. Nicaragua]                     7.808e+04   1.76e+04      4.441      0.000    4.36e+04    1.13e+05
country[T. Outlying-US(Guam-USVI-etc)]   -4436.5676   2.69e+04     -0.165      0.869   -5.72e+04    4.83e+04
country[T. Peru]                          8.042e+04   1.83e+04      4.383      0.000    4.45e+04    1.16e+05
country[T. Philippines]                   1.313e+04   9058.043      1.449      0.147   -4625.297    3.09e+04
country[T. Poland]                       -7716.3620   1.35e+04     -0.571      0.568   -3.42e+04    1.88e+04
country[T. Portugal]                     -4.189e+04    1.7e+04     -2.471      0.013   -7.51e+04   -8659.074
country[T. Puerto-Rico]                   1.103e+04   1.03e+04      1.074      0.283   -9092.877    3.12e+04
country[T. Scotland]                     -2.354e+04    2.9e+04     -0.812      0.417   -8.04e+04    3.33e+04
country[T. South]                         1.657e+04   1.25e+04      1.326      0.185   -7928.742    4.11e+04
country[T. Taiwan]                        3.384e+04    1.5e+04      2.251      0.024    4374.171    6.33e+04
country[T. Thailand]                      3.695e+04   2.41e+04      1.536      0.125   -1.02e+04    8.41e+04
country[T. Trinadad&Tobago]              -7783.7596   2.32e+04     -0.335      0.737   -5.33e+04    3.77e+04
country[T. United-States]                -1.003e+04   4233.276     -2.369      0.018   -1.83e+04   -1733.026
country[T. Vietnam]                       9889.5231   1.34e+04      0.736      0.462   -1.64e+04    3.62e+04
country[T. Yugoslavia]                    2.538e+04   2.52e+04      1.007      0.314    -2.4e+04    7.48e+04
salary[T. >50K]                           5044.1495   1616.147      3.121      0.002    1876.441    8211.858
census[T.Bajo]                           -7.506e+05   1.57e+04    -47.686      0.000   -7.81e+05    -7.2e+05
education_yrs                             1.035e+04    425.173     24.340      0.000    9515.219    1.12e+04
capital_gain                                 0.0688      0.078      0.885      0.376      -0.084       0.221
capital_lost                                -1.2514      1.391     -0.900      0.368      -3.977       1.475
hours_week                                -130.2184     49.685     -2.621      0.009    -227.604     -32.833
==============================================================================
Omnibus:                     5179.250   Durbin-Watson:                   2.009
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9972.041
Skew:                           0.991   Prob(JB):                         0.00
Kurtosis:                       4.851   Cond. No.                     1.47e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

R-cuadrado = Variación explicada / variación total
El R-cuadrado siempre está entre 0 y 100%:
0% indica que el modelo no explica ninguna porción de la variabilidad de los datos de respuesta en torno a su media.
100% indica que el modelo explica toda la variabilidad de los datos de respuesta en torno a su media.

**Interpretación del summary**

- **R-square:** Siempre se encuentra entre el 0 y el 100%, el nuestro está en 0.117, por lo tanto, esto nos quiere decir que la variables presidctoras explican en un 11,7% nuestra variable respuesta.
- **coef:** Estos datos nos indican cuánto son afectadas las variables por las que se relacionan con ellas. Vemos que las afectaciones son mínimas, de muy poquitas milésimas, tanto en positivo como en negativo.
- **std err:** Esta columna nos está diciendo que tenemos un gran margen de error en la estimación del coeficiente, seguramente debido a la cantidad de ouliers.
- **t:** Es el resultado de dividir los dos valores anteriores. Con esto estamos intentando averiguar en qué medida la afectación de los datos entre sí influye en el margen de error, es decir, si las variables se influyen también cuando no tienen correlación (or something???).